### ISSUE TITLE
Throw an error on Node.js 20.x

### ISSUE THREAD

**Issue by yusukebe** [ysugimoto/vite-plugin-fastly-js-compute#1]
Hi. Thank you for creating a great module!

I've tested it with Hono's tests, but it throws an error on Node.js 20.x:

<img width="809" alt="Screenshot 2023-12-17 at 12 02 48" src="https://github.com/ysugimoto/vite-plugin-fastly-js-compute/assets/10682/5508165b-2e09-4967-9f49-0d3c4239db8e">

The issue arises because Node.js 20.x already includes its own `crypto` globally, so it shouldn't be polyfilled if the Node.js runtime has `crypto`.

**Comment by ysugimoto** [comment]
This problem is fixed on https://github.com/ysugimoto/vite-plugin-fastly-js-compute/pull/2
To solve it, suppress polyfill `globalThis.crypto` if the object already exists.

Unfortunately, nodejs20's crypto (WebCrypto) has too many features, it should be nice, but Fastly Comoute's crypto should not have all the features to keep compatibility so I also updated Hono's tests a bit.
